/* personal-assistant-thing/src/lib/ollama.ts */
// Wrapper using the official Ollama npm package.

import ollama from "ollama";

/**
 * Sends a prompt to the Ollama model and returns the generated response.
 *
 * @param prompt - The text prompt to send to the model.
 * @param model - The Ollama model to use. Defaults to 'gpt-oss'.
 * @returns The text generated by the model.
 * @throws If the request fails.
 */
export async function fetchOllamaResponse(
  prompt: string,
  model = "gpt-oss",
): Promise<string> {
  const result = await ollama.generate({ model, prompt });
  // The official package returns an object with a `response` field.
  // Adjust if the shape differs.
  // @ts-ignore
  return result.response;
}
