// personal-assistant-thing/src/lib/ollama.ts
// Simple wrapper around Ollama's local server.

export interface OllamaGenerateResponse {
  model: string;
  created_at: string;
  response: string;
  done: boolean;
  // Other fields omitted for brevity.
}

/**
 * Sends a prompt to the local Ollama server and returns the generated response.
 *
 * @param prompt - The text prompt to send to the model.
 * @param model - The Ollama model to use. Defaults to 'gpt-oss'.
 * @returns The text generated by the model.
 * @throws If the request fails or the server returns an error status.
 */
export async function fetchOllamaResponse(
  prompt: string,
  model = "gpt-oss",
): Promise<string> {
  const url = "http://localhost:11434/api/generate";

  const payload = {
    model,
    prompt,
    stream: false, // We want a single response, not a stream.
  };

  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Ollama API error (${res.status}): ${errorText}`);
  }

  const data: OllamaGenerateResponse = await res.json();
  return data.response;
}
